### ISSUE TITLE
No Athena type available in Managed Graphana "Add Data Source" dialog

### ISSUE THREAD

**Issue by aorcl** [aws-samples/aws-batch-operational-dashboards#28]
Hello, 
After deploying the solution today, trying to follow up the guide and at the step requiring adding an Athena datasource I'm unable to do so: 
the Athena doesn't appear as datasource type available to add.
The previous datasource (Cloudwatch) was added successfully but not this one.

Are there prerequisites missing for the Athena to become available as datasource?

**Comment by mhuguesaws** [comment]
Apologies for not answering earlier.

It is due to a change with Amazon Managed Grafana 9.4. You will need to have the changes from this pull request https://github.com/aws-samples/aws-batch-operational-dashboards/commit/16af59f8662d5b4047ee96714cdb31f46a60f2df to have `PluginAdminEnabled` enabled.

Amazon Managed Grafana since version 9.4 comes with Prometheus and Cloudwatch plugin enabled by default. For other plugins such as Amazon Athena, you will need to install them with the following procedure:


1. Select the **hamburger** menu on the left pane.
1. Expand **Administration**
1. Choose **Plugins**.
1. Search **Amazon Athena**.
1. Choose **Install**.

Wait for the plugin to be installed. Once completed, you can add Amazon Athena as a data source.

Let me know if that works for you or if you have additional questions. We'll add those steps to the documentation.

**Comment by aorcl** [comment]
thanks a lot
